### PR TITLE
Fix #1 (Bad language)

### LINKED ISSUE #1: Bad english
Please fix that asap.

### LINKED ISSUE #4: English pls
**You still haven't fixed the readme file. I want to die.**

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes #1.

### CODE REVIEW

**Review by FssAy — APPROVED** [review]
👍

**Review by efindus — APPROVED** [review]

**Comment by Mondonno** [comment]
Ok, i review this

**Comment by uqlel** [comment]
I nadal zjebany angielski lmao XD

**Comment by uqlel** [comment]
mikolaj.mocek@icloud.com btw

**Review by Mondonno — CHANGES_REQUESTED** [review]
Conflicting with current branch and current stage

**Comment by Mondonno** [comment]
Still no changes here, closing.

**Pull request closed without merging**
